In [1]:
import pandas as pd

In [2]:
!pip install dependency  # Replace './dependency' with the actual path if it's a local module

Collecting dependency
  Downloading dependency-0.0.3.tar.gz (3.4 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: dependency
  Building wheel for dependency (setup.py) ... done
  Created wheel for dependency: filename=dependency-0.0.3-py3-none-any.whl size=3959 sha256=91374401a9364631cabecb1594d83e44308049d81bc1958cbe256e8f9310ffa7
  Stored in directory: /root/.cache/pip/wheels/75/e8/aa/3e5de7cac8c39b8d40eb478b033cdaa25a8672e18ab55c17e2
Successfully built dependency
Installing collected packages: dependency
Successfully installed dependency-0.0.3

In [3]:
import dependency as dp

In [4]:
  import numpy as np
  import matplotlib.pyplot as plt
  import seaborn as sns
  import sklearn.model_selection as ms
  from sklearn.linear_model import LinearRegression
  from sklearn.metrics import mean_squared_error

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [7]:
### Loading the dataset to a pandas datafrme
Credit_card_data = pd.read_csv('/creditcard.csv')

In [8]:
Credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [9]:
Credit_card_data.shape

(284807, 31)

In [10]:
Credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [11]:
##chechkiing the missing value in each coloumn
Credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [12]:
## distributed the legit transection and froudness transection
Credit_card_data['Class'].value_counts()
### 0 = legit transection , 1 = froudness transection

Class
0    284315
1       492
Name: count, dtype: int64

In [13]:
### sparating the data for analysis
legit = Credit_card_data[Credit_card_data.Class == 0]
froud = Credit_card_data[Credit_card_data.Class == 1]

In [14]:
### Statical measure of the data
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [15]:
froud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [16]:
### compare the value for both transection
Credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [17]:
### undersampling  ### build a sample dataset containing similer distribution of normal
legit_sample = legit.sample(n=492)

In [18]:
from types import new_class
## concatenting 2 dataset
new_dataset = pd.concat([legit_sample, froud], axis=0) ### axix 0 means rows axis 1 means coloumn

In [19]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,95634.510163,-0.068901,-0.024388,-0.003621,0.027072,0.083623,-0.029770,-0.012844,0.012508,-0.041994,...,-0.072795,-0.038165,-0.030741,0.048764,0.040596,-0.007237,0.022115,0.022142,-0.001606,78.417378
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [20]:
from re import X
## spliting the data into feature and targets
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [21]:
print(X)

            Time        V1        V2        V3        V4        V5        V6  \
180884  124735.0  2.044173  0.337590 -1.558132  1.374245  0.534499 -1.125713
250157  154756.0  0.095980 -0.176602  0.921670 -1.141363 -0.599712 -0.214727
265116  161747.0 -0.821797  0.725557  0.466154 -1.217991  0.378543  0.686101
280163  169359.0  2.130195 -0.587329 -1.041774 -0.580669 -0.729121 -0.811544
280358  169475.0  2.063551  0.039971 -1.034999  0.406308 -0.039092 -1.190294
...          ...       ...       ...       ...       ...       ...       ...
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7        V8        V9  ...       V20       V21       V22  \
180884  0.710897 -0.481855  0.031748  ... -0.244963  0.058321  0.470760
250157  0.298571 -0.036773 -0.736961  ... -0.316996 -0.430995 -0.847823
265116  1.506102 -0.102398 -0.370890  ... -0.193627  0.031862  0.130287
280163 -0.908433 -0.112427 -0.072835  ...  0.069059  0.265522  0.876840
280358  0.266879 -0.404669  0.356531  ... -0.147678 -0.274981 -0.597416
...          ...       ...       ...  ...       ...       ...       ...
279863 -0.882850  0.697211 -2.064945  ...  1.252967  0.778584 -0.319189
280143 -1.413170  0.248525 -1.127396  ...  0.226138  0.370612  0.028234
280149 -2.234739  1.210158 -0.652250  ...  0.247968  0.751826  0.834108
281144 -2.208002  1.058733 -1.632333  ...  0.306271  0.583276 -0.269209
281674  0.223050 -0.068384  0.577829  ... -0.017652 -0.164350 -0.295135

             V23       V24       V25       V26       V27       V28  Amount
180884 -0.008681  0.022854  0.499051 -0.492445 -0.005840 -0.060920    1.00
250157  0.518148  1.003485 -0.732474 -0.794278  0.071624  0.044746   95.00
265116 -0.255104  0.138029  0.013833  0.093147 -0.112604  0.092514  169.80
280163  0.189644  1.005213 -0.168487 -0.142375  0.033508 -0.001142   10.79
280358  0.327141  0.079637 -0.258171  0.191354 -0.062662 -0.057318    1.29
...          ...       ...       ...       ...       ...       ...     ...
279863  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00
280143 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76
280149  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89
281144 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00
281674 -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53

[984 rows x 30 columns]

In [ ]:
print(Y)

1213    0.0
1646    0.0
499     0.0
77      0.0
910     0.0
       ...
978     0.0
1752    0.0
809     0.0
541     1.0
623     1.0
Name: Class, Length: 494, dtype: float64

In [22]:
## splite the data into traing data and testing data

In [23]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [24]:
print(X.shape, X_train.shape, X_test.shape)

(984, 30) (787, 30) (197, 30)

In [25]:
## model training
##LogisticRegression
model = LogisticRegression()

In [26]:
##traing the logistics regression model with Training data
model.fit(X_train, Y_train)

LogisticRegression()

In [27]:
## accuracy on traing data

X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [28]:
print('Accuracy on training data : ', training_data_accuracy)

Accuracy on training data :  0.9237611181702668

In [29]:
### accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [30]:
print('Accuracy on test data : ', test_data_accuracy)

Accuracy on test data :  0.8883248730964467